using System.Net;
using System.Net.Mail;

namespace AutomatedFinancialLedgerAPI.Services;

/// <summary>
/// Sends transactional emails (e.g. password reset links).
/// In development, if SMTP is not configured the message is logged
/// instead of sent so the flow remains testable end-to-end.
/// </summary>
public interface IEmailService
{
      Task SendPasswordResetAsync(string toEmail, string fullName, string resetLink, CancellationToken ct = default);
}

public class EmailService : IEmailService
{
    private readonly IConfiguration _config;
        private readonly ILogger<EmailService> _logger;

            public EmailService(IConfiguration config, ILogger<EmailService> logger)
                {
                        _config = config;
                                _logger = logger;
                                    }

                                        public async Task SendPasswordResetAsync(string toEmail, string fullName, string resetLink, CancellationToken ct = default)
                                            {
                                                    var host = _config["Smtp:Host"];
                                                            var portStr = _config["Smtp:Port"];
                                                                    var user = _config["Smtp:User"];
                                                                            var pass = _config["Smtp:Password"];
                                                                                    var from = _config["Smtp:From"] ?? user;

                                                                                            var subject = "Reset your Automated Financial Ledger password";
                                                                                                    var body =
                                                                                                                $"Hi {fullName},\r\n\r\n" +
                                                                                                                            "We received a request to reset your password. " +
                                                                                                                                        "If you did not make this request you can safely ignore this email.\r\n\r\n" +
                                                                                                                                                    $"Reset your password (link expires in 1 hour):\r\n{resetLink}\r\n\r\n" +
                                                                                                                                                                "-- Automated Financial Ledger API\r\n";
                                                                                                                                                                
                                                                                                                                                                        if (string.IsNullOrWhiteSpace(host) || string.IsNullOrWhiteSpace(portStr) || string.IsNullOrWhiteSpace(from))
                                                                                                                                                                                {
                                                                                                                                                                                            // Dev / unconfigured fallback: log instead of send so the flow is testable.
                                                                                                                                                                                                        _logger.LogWarning(
                                                                                                                                                                                                                        "SMTP not configured. Password reset email NOT sent. To: {To}, Link: {Link}",
                                                                                                                                                                                                                                        toEmail, resetLink);
                                                                                                                                                                                                                                                    return;
                                                                                                                                                                                                                                                            }
                                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                                    if (!int.TryParse(portStr, out var port))
                                                                                                                                                                                                                                                                            {
                                                                                                                                                                                                                                                                                        _logger.LogError("Invalid Smtp:Port value '{Port}'. Email not sent.", portStr);
                                                                                                                                                                                                                                                                                                    return;
                                                                                                                                                                                                                                                                                                            }
                                                                                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                                                                                    using var client = new SmtpClient(host, port)
                                                                                                                                                                                                                                                                                                                            {
                                                                                                                                                                                                                                                                                                                                        EnableSsl = true,
                                                                                                                                                                                                                                                                                                                                                    DeliveryMethod = SmtpDeliveryMethod.Network,
                                                                                                                                                                                                                                                                                                                                                                UseDefaultCredentials = false,
                                                                                                                                                                                                                                                                                                                                                                            Credentials = string.IsNullOrEmpty(user) ? null : new NetworkCredential(user, pass)
                                                                                                                                                                                                                                                                                                                                                                                    };
                                                                                                                                                                                                                                                                                                                                                                                    
                                                                                                                                                                                                                                                                                                                                                                                            using var message = new MailMessage(from, toEmail, subject, body)
                                                                                                                                                                                                                                                                                                                                                                                                    {
                                                                                                                                                                                                                                                                                                                                                                                                                IsBodyHtml = false
                                                                                                                                                                                                                                                                                                                                                                                                                        };
                                                                                                                                                                                                                                                                                                                                                                                                                        
                                                                                                                                                                                                                                                                                                                                                                                                                                try
                                                                                                                                                                                                                                                                                                                                                                                                                                        {
                                                                                                                                                                                                                                                                                                                                                                                                                                                    await client.SendMailAsync(message, ct);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                _logger.LogInformation("Password reset email sent to {To}", toEmail);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                        }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                catch (Exception ex)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    // Never surface SMTP errors to the API caller -- avoids user enumeration.
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                _logger.LogError(ex, "Failed to send password reset email to {To}", toEmail);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            
